#!/usr/bin/env bash

taxon="$1"

export LC_ALL=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8

read -d '' q <<EOF
SELECT platform.accession
FROM platform
INNER JOIN taxon
ON platform.taxon_id=taxon.id
WHERE taxon.accession='$taxon'
EOF

#mkdir -p "$output"/{sample,gene}

{
    for gpl in $(btkdb query "$q"); do
        dataset matrix gene "$gpl" 2> /dev/null
    done
}   | grep -v '^$' | {
    head -1
    grep '^GSM'
}   
    #| tee >(mmat load "$output"/sample/raw) \
    #| tee >(dm transpose | mmat load "$output"/gene/raw) \
    #| dm pmap log-transform \
    #| dm pmap standardize \
    #| tee >(mmat load "$output"/sample/normalized) \
    #| dm transpose \
    #| mmat load "$output"/gene/normalized
