#!/usr/bin/env bash

taxon="$1"
output="$2"

read -d '' q <<EOF
SELECT platform.accession
FROM platform
INNER JOIN taxon
ON platform.taxon_id=taxon.id
WHERE taxon.accession='$taxon'
EOF

#accessions=$(mktemp)
#trap 'rm -f $accessions' EXIT
#btkdb query "$q" > $accessions

mkdir -p "$output"/{raw,normalized}

{
    for gpl in $(btkdb query "$q"); do
        dataset matrix gene "$gpl" 2> /dev/null
    done
}   | grep -v '^$' | {
    head -1
    grep '^GSM'
}   | tee >(dm transpose | mmat load "$output"/raw) \
    | dm pmap log-transform \
    | dm pmap standardize \
    | dm transpose \
    | mmat load "$output"/normalized

