#!/usr/bin/env bash

usage() {
    cat <<EOF 1>&2
Extract an expression matrix from a GEO MiniML archive.

USAGE: $0 <options> archive-path

options:
  -v : verbose output
  -h : show this help
EOF
    exit 1
}

mkdir -p $HOME/.cache/btk/
export tmpdir=$(mktemp -d -p $HOME/.cache/btk/)

trap 'rm -rf $tmpdir' EXIT
mkdir -p $tmpdir/expression
find $tmpdir -type d -exec chmod a+rx {} \;

shopt -s nullglob

verbose=

while getopts ncvh opt; do
    case $opt in
        v) verbose=y ;;
        h) usage ;;
    esac
done

shift $((OPTIND - 1))
[[ $# != 1 ]] && usage

export archive="$1"
export verbose

process() {
    file="$1"
    gsm=$(basename ${file%%-*})
    if [[ $verbose == "y" ]]; then
        echo "** Processing $gsm ..." 1>&2
    fi
    echo -ne "$gsm\t"
    cut -f1-2 $file \
        | tawk '$2 !~ /[^0-9.\-Ee]/' \
        | sort -k1,1b \
        | join -o 1.2 -t '	' -a 2 - $tmpdir/probes \
        | awk 'NF == 0 { print "NaN" } NF == 1 { print $1 }' \
        | tr '\n' '\t' \
        | sed 's/\t$//'
    echo
    rm $file
}
export -f process

{
    # This rate limiting is chosen to try and keep the expression directory relatively small
    #rate=4m
    #| pv -qL $rate \
    #catwhile -p "$tmpdir" -s 1000 < "${archive}" \
    cat "${archive}" \
        | bsdtar -C $tmpdir/expression -x -f - 'GSM*-1.txt'
    touch "$tmpdir"/done
} &

echo "Working directory =" $tmpdir 1>&2
accession=$(bsdtar qtf ${archive} '*_family.xml' | sed 's/_family.xml$//')
#if [[ $accession != "GPL*"]]; then
#    echo "ERROR: Malformed MiniML archive. Exiting..." 1>&2
#fi
echo "Detected accession =" $accession 1>&2

echo "* Unpacking probes ..." 1>&2
bsdtar -q -xOf ${archive} 'GPL*.txt' \
    | cut -f1 | sort -k1,1b > $tmpdir/probes || exit 1

echo "* Exporting expression vectors ..." 1>&2

echo -ne 'Probe ID\t'
tr '\n' '\t' < $tmpdir/probes | sed 's/\t$//'
echo

while true; do
    find $tmpdir/expression -type f \
        | parallel process
    if [ -e "$tmpdir/done" ]; then
        break
    fi
    sleep 1
done
