#!/usr/bin/env bash

DATA_DIR=${DATA_DIR-$HOME/data}

sql="$(dirname $0)/sql/${1}.sql" 

if [ -e "$sql" ]; then
    sqlite3 -header -csv \
        $DATA_DIR/bioconductor/GEOmetadb.sqlite \
        "$(cat $sql)" \
        | csv2tsv
else
    exit 1
fi
