language: python
python:
    - "3.3"
virtualenv:
    system_site_packages: true
install: 
    - sudo apt-get install -y gfortran libhdf5-serial-dev libblas-dev liblapack-dev libatlas-dev libatlas-base-dev 2> /dev/null
    - pip install numpy scipy 2> /dev/null
    - pip install -r requirements.txt
    - python setup.py install
script: 
    - python setup.py test
