language: python
python:
    - "3.3"
install: 
    - sudo apt-get install python3-numpy python3-scipy libhdf5 libhdf5-dev
    - pip install -r requirements.txt
    - python setup.py install
script: 
    - python setup.py test
