language: python
python:
    - "3.3"
install: 
    - sudo add-apt-repository -y ppa:pythonxy/pythonxy-devel
    - sudo apt-get update
    - sudo apt-get install -y python3-numpy python3-scipy libhdf5-serial-dev
    - ln -s /usr/lib/python3.3/dist-packages/numpy ~/virtualenv/python3.3/lib/python3.3/site-packages/
    - ln -s /usr/lib/python3.3/dist-packages/scipy ~/virtualenv/python3.3/lib/python3.3/site-packages/
    - pip install -r requirements.txt
    - python setup.py install
script: 
    - python setup.py test
