language: python
python:
    - "3.3"
virtualenv:
    system_site_packages: true
install: 
    - pip install numpy
    - sudo apt-get install -y python3-scipy libhdf5-serial-dev
    - pip install -r requirements.txt
    - python setup.py install
script: 
    - python setup.py test
