language: python
python:
    - "3.2"
    - "3.3"
install: 
    - sudo apt-get install python3-numpy python3-scipy python3-pandas hdf5 cython3
    - pip install -r requirements.txt
    - python setup.py install
script: 
    - python setup.py test
