language: python
python:
    - "3.2"
    - "3.3"
install: 
    - sudo apt-get install hdf5 python3-numpy python3-scipy cython3
    - pip install -r requirements.txt
    - python setup.py install
script: 
    - python setup.py test
