language: python
python:
    - "3.3"
virtualenv:
    system_site_packages: true
install: 
    - sudo apt-get install -y gfortran libhdf5-serial-dev libblas-dev liblapack-dev
    - pip install numpy scipy
    - pip install -r requirements.txt
    - python setup.py install
script: 
    - python setup.py test
