#!/usr/bin/env python

import sys

import numpy as np
import pandas as pd
import pylab as pl
from matplotlib.pyplot import savefig

pl.rcParams.update({"font.size": 6})
data = pd.read_table(sys.stdin, 
        sep="\t", header=None, index_col=0)
ix = data.index
fig = pl.figure()
ax = pl.subplot(111)
ax.barh(range(len(ix)), data.iloc[:,0])
width = 1
ax.set_yticks(np.arange(len(ix)) + width / 2)
ax.set_yticklabels(ix)
fig.tight_layout()
fig.savefig(sys.stdout, dpi=300, format="png")
