#!/usr/bin/env python3

import sys
import argparse

import numpy as np
from matplotlib.pyplot import savefig

from BioTK.plot import histogram

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--title","-t")
    p.add_argument("--x-label","-x")
    p.add_argument("--y-label","-y")
    p.add_argument("--color","-c", default="blue")
    p.add_argument("--bins","-b", default=20, type=int)
    p.add_argument("--min","-l", type=float)
    p.add_argument("--max","-u", type=float)
    p.add_argument("--format","-f",default="png")
    p.add_argument("data_file", nargs="?", 
            type=argparse.FileType("r"),
            default=sys.stdin)
    args = p.parse_args()

    with args.data_file as h:
        data = []
        for line in h:
            try:
                x = float(line)
                if np.isnan(x):
                    continue
                data.append(x)
            except ValueError:
                continue
        data = np.array(data)

    if args.min is None:
        args.min = np.min(data)
    if args.max is None:
        args.max = np.max(data)

    data = data[data >= args.min]
    data = data[data <= args.max]
    data = np.log(data)
   
    fig = histogram(data, 
            bins=args.bins, x_label=args.x_label,
            y_label=args.y_label, title=args.title,
            color=args.color)
    savefig("/dev/stdout", format=args.format)
