#!/usr/bin/env python

import sys

import pandas as pd

X = pd.read_table(sys.stdin, index_col=0)\
        .dropna(axis=1, thresh=25)\
        .dropna(axis=0, how="all")
X.corr().to_pickle(sys.argv[1])
