#!/usr/bin/env python

import argparse

from fisher import pvalue

p = argparse.ArgumentParser()
p.add_argument("group1", type=argparse.FileType("r"))
p.add_argument("group2", type=argparse.FileType("r"))
args = p.parse_args()

items = lambda xs: set(x.strip() for x in xs)
g1 = items(args.group1)
g2 = items(args.group2)

a = len(g1 & g2)
b = len(g1 - g2)
c = len(g2 - g1)
d = sum([a,b,c] - len(g2 | g1))
odds_ratio = (a * d) / (b * d)

two_tail = pvalue(a,b,c,d)[2]
print("Odds Ratio", odds_ratio, sep="\t")
print("P-Value", two_tail, sep="\t")
