#!/usr/bin/env python

import argparse
import sys

import pandas
import numpy as np
from numpy.linalg import lstsq
from scipy.stats import pearsonr

p = argparse.ArgumentParser()
p.add_argument("y", type=int)
p.add_argument("x", type=int)
args = p.parse_args()

X = pandas.read_table(sys.stdin, header=None)
xy = X.iloc[:,[args.x-1,args.y-1]].as_matrix()
ix = [i for i in range(X.shape[1]) if i not in (args.x,args.y)]
X = X.iloc[:,ix].as_matrix()
X = np.append(np.ones(X.shape[0]).reshape(X.shape[0],1), X, axis=1)

m = lstsq(X,xy)[0]
residual = np.dot(X,m) - xy
r, p = pearsonr(residual[:,0], residual[:,1])
print(r, p)
