#!/usr/bin/env bash

HOST=0.0.0.0
PORT=13512
DATADIR="$(pwd)"

while getopts h:p: opt; do
    case $opt in
        h) HOST=$OPTARG ;;
        p) PORT=$OPTARG ;;
        d) DATADIR=$OPTARG ;;
    esac
done
shift $((OPTIND -1 ))

tcpserver $HOST $PORT $(dirname $0)/xmatd-worker 
