#!/usr/bin/env bash

# name: xmat
# description: Store and query a tab-delimited matrix in a indexed pixz archive

_load_t() {
    awk '
        BEGIN {
            OFS="\n"
            FS="\t"
        }
        NR == 1 {
             for (i=2; i<=NF; i++) {
                print $i >> "index/rows"
            }
        }
        NR > 1 {
            for (i=2; i<=NF; i++) {
                print $i >> "columns/"$1
            }
        }'
}

load() {
    path=$(realpath $1)
    wd=$(mktemp -d)
    cd $wd
    mkdir index rows columns
    tee >(dm transpose | _load_t) | awk '
        BEGIN {
            OFS="\n"
            FS="\t"
        }
        NR == 1 { 
            print $1 > "index/name"
            for (i=2; i<=NF; i++) {
                print $i >> "index/columns" 
            }
        }
        NR > 1 { 
            for (i=2; i<=NF; i++) {
                print $i >> "rows/"$1
            }
        }'
    tar cf - * | pixz -o $path
    cd - 2> /dev/null
    rm -r $wd
}

_extract() {
    pixz -x -i "$1" "$2" | tar -xO
}

_to_row() {
    perl -i -pe 'chomp if eof' | tr '\n' '\t'
    echo
}

dump() {
    path=$(realpath $1).xmat
    { 
        _extract $path index/name
        _extract $path index/columns
    } | _to_row
    _extract $path index/rows | while read ix; do
        {
            echo "$ix"
            _extract $path rows/"$ix"
        } | _to_row
    done
}

cmd="$1"
shift 1
$cmd "$@" 2>/dev/null
