[package]
name = "btk"
version = "0.1.0"
authors = [ "mail@corygil.es" ]

[lib]
name = "btk"

[dependencies.leveldb]
git = "https://github.com/gilesc/rust-leveldb.git"

[dependencies.msgpack]
git = "https://github.com/mneumann/rust-msgpack.git"
