#!/usr/bin/env bash

source $(dirname $0)/BioTK.sh

ASPERA_HOME=$HOME/.aspera/connect

( [[ $# -eq 0 ]] || [[ $1 == "-h" ]] || [[ $1 == "--help" ]] ) && {
    {
        echo "Download a file or directory using Aspera Connect."
        echo
        echo "USAGE: $(basename $0) RHOST:RPATH LPATH" 
    } 1>&2
    exit 0
}

if [ ! -e "$ASPERA_HOME" ]; then
    version=3.4.2.90351
    os=$(uname)
    platform=$(uname -m)
    if on_intranet; then
        url_base="http://wren.omrf.hsc.net.ou.edu"
    else
        url_base="http://wrenlab.org"
    fi
    url="${url_base}/private/BioTK/"
    url+="aspera-connect-${version}-${os}-${platform}.tgz"
    echo "Attempting to install Aspera Client..."
    echo -e "\t* $url"
    {
        curl --user BioTK:BioTK $url || {
            echo "Aspera Client cannot be automatically installed for your platform, which has been detected as: ${os} ${platform}" 1>&2
            exit 1
        } 
    } | tar -C $HOME -xz
fi

speed=250M
key=$ASPERA_HOME/etc/asperaweb_id_dsa.openssh

cmd="$ASPERA_HOME/bin/ascp -T -i $key -l $speed $@"
sem --no-notice -j1 --fg --id ascp "$cmd"
