#!/usr/bin/env python3

# FIXME: allow plotting multiple series (a dataframe as input)

import argparse
import sys

import numpy as np
import pandas as pd
import pylab as pl

import BioTK.plot

p = BioTK.plot.argparse_template()
p.add_argument("--horizontal", action="store_true")
args = p.parse_args()

y = pd.read_csv(sys.stdin, sep="\t", index_col=0, header=None)
nc = y.shape[1]
assert nc in (1,2)
data = y.iloc[:,0]
args.error = y.iloc[:,1] if nc == 2 else None

BioTK.plot.barplot.cli(args, data)
