#!/usr/bin/env bash

ailun() {
    urlcache "ftp://ailun.stanford.edu/ailun/annotation/geo/${1}.annot.gz" \
        | gzip -dc
}

entrez-gene-info() {
    urlcache 'ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene_info.gz' | gzip -dc
}

_owl() {
    ns=$(echo "$1" | tr '[A-Z]' '[a-z]')
    url="http://purl.obolibrary.org/obo/${ns}.owl"
    urlcache -p "$url"
}

obo-names() {
    echo -e "ID\tName"
    owltools $(_owl "$1") \
        --object-to-label-table \
        | sed 's/\/\([A-Za-z_0-9]*\t\)/\t\1/' \
        | cut -f2-3 \
        | awk 'BEGIN {OFS=FS="\t"} {gsub("_",":",$1); print;}'
}

obo-links() {
    echo -e "Child\tParent"
    owltools $(_owl "$1") --write-all-subclass-relationships
}

GEOmetadb() {
    urlcache -p -f 'gzip -dc' 'http://gbnci.abcc.ncifcrf.gov/geo/GEOmetadb.sqlite.gz'
}

cmd="$1"
shift 1
$cmd "$@"
