#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "USAGE: $0 outfile < input"
    echo "Useful for overwriting an input file with a command."
fi 1>&2

tmp=$(mktemp)
trap 'rm -f $tmp' EXIT
gzip > $tmp
zcat $tmp > "$1"
