#!/usr/bin/env python

import sys

import pandas
import numpy

delimiter = "\t"
X = pandas.read_csv(sys.argv[1], sep=delimiter, 
        index_col=0)
Y = pandas.read_csv(sys.argv[2], sep=delimiter, 
        index_col=0)
X, Y = X.align(Y, axis=0)

rows = []
for col in Y.columns:
    rows.append(X.corrwith(Y[col]))

pandas.DataFrame(rows, index=Y.columns).to_csv(sys.stdout, sep=delimiter)
