#!/usr/bin/env python3

import csv
import sys

# Don't throw broken pipe error at EOF
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE,SIG_DFL)

reader = csv.reader(sys.stdin)
for row in reader:
    print(*[x.replace("\n", "; ").replace("\t", " ")
        for x in row], sep="\t")
