#!/usr/bin/env bash

# Generic data manipulation

source $(dirname $0)/BioTK.sh

cmd="$1"

which dm-"$cmd" &> /dev/null || {

    cat 1>&2 <<EOF
dm - Manipulation tools for tabular data

Available subcommands:

    collapse - collapse a matrix using an identifier map
    correlate - correlate columns in a matrix
    view - view the first few rows and columns
EOF
    exit 0
}

shift
dm-${cmd} "$@"
