#!/usr/bin/env python3

import sys
import gzip
from functools import compose

import numpy as np

def gzopen(path):
    if path.endswith(".gz"):
        return gzip.open(path, "rt")
    else:
        return open(path)

def as_float(x):
    try:
        return float(x)
    except ValueError:
        return np.nan

columns = set()
for path in sys.argv[1:]:
    with gzopen(path) as h:
        for c in next(h).strip("\n").split("\t")[1:]:
            columns.add(c)

columns = list(sorted(columns))
index = compose(dict,zip,map,reversed,enumerate)
columns_ix = index(columns)
print("", *columns, sep="\t")

for path in sys.argv[1:]:
    with gzopen(path) as h:
        m = {}
        for i,c in next(h).strip("\n").split("\t")[1:]:
            j = columns_ix[c]
            m[i] = j

        for line in h:
            key, *data = line.strip("\n").split("\t")
            xs = np.empty(len(columns))
            for i,x in enumerate(data):
                xs[m[i]] = as_float(x)
            print(key, *xs, sep="\t")
