#!/usr/bin/env bash

# FIXME: make a more general "groupby" to replace collapse

###################
# Utility functions
###################

run-ignore-header() {
    IFS='' read header
    echo "$header"
    "$@"
}

##########
# Main CLI
##########

cmd="$(dirname $0)/dt-$1"
shift

if [[ ! -f "$cmd" ]]; then
    cat <<EOF 1>&2
dt - utility for operating on tab-delimited matrices or tables

USAGE: dt [command] [args]

General:
 view	View the first few rows and columns of the table
 sort	Sort a tabular dataset, excluding the header
 cut	Select fields by name or position
 map	Run a command on each row of a matrix
 cat	Format a matrix, returning its data unchanged
 filter	Remove rows with too few valid values
 wrap	Wrap a command to return the matrix header unmodified, 
            then operate on rows, possibly in parallel
 pivot	Convert a sparse matrix in 3-column format to dense
            or a "list" format

Normalization and other preprocessing:
 log			Log-transform rows
 qnorm			Quantile normalize a matrix
 standardize	Standardize (scale) the rows of a matrix
 impute			Impute missing values using Hastie's 
                    softImpute method

Correlation and similarity:
 correlate	Produce the pairwise correlation matrix of columns
 corrwith	Correlate each row in a matrix with a vector
 dot		Take the dot product of matrices or vectors

Aggregation and grouping:
 collapse	Collapse a matrix using a mapping of row IDs
 union		SQL-like union of multiple sets of tabular data
 split		Split a table into files based on a column and mapping

Statistics:
 summary	Print summary statistics for each row

Sampling:
 random	Generate a random vector or matrix
 sample	Sample rows of a matrix with a given probability

Serialization:
 pickle	Serialize a tab-delimited matrix
 unpickle Convert a serialized matrix to tab-delimited format
EOF
    exit 1
fi

# TODO: add individual helps for commands

$cmd "$@"
