#!/usr/bin/env bash

dt wrap -p dt normalize --no-header -m standardize \
    | dt filter-empty \
    | transpose \
    | dt wrap -p dt normalize --no-header -m standardize \
    | dt filter-empty \
    | transpose
