#!/usr/bin/env bash

dt wrap -p dt normalize --no-header -m standardize \
    | dt filter \
    | transpose -n \
    | dt wrap -p dt normalize --no-header -m standardize \
    | dt filter \
    | transpose -n
