#!/usr/bin/env python3

# Correlate the rows of a matrix with an input vector
# (in tab-delimited key-value format).

import sys
import argparse

import numpy as np
import pandas as pd
from scipy.stats import pearsonr

from BioTK.io import read_matrix, read_vector
import fmio

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("vector",
                   type=argparse.FileType("r"))
    p.add_argument("--verbose", "-v", action="store_true")
    p.add_argument("--binary", "-b", action="store_true")
    p.add_argument("--print-all", "-a", action="store_true",
        help="Output NaN correlations.")
    args = p.parse_args()

    vector = read_vector(args.vector).dropna()
    if args.binary:
        matrix = fmio.Reader(sys.stdin.buffer)
    else:
        matrix = read_matrix(sys.stdin)

    print("", "N", "Correlation", "-log10(P-Value)",
          sep="\t")
    for row in matrix:
        q, v = row.dropna().align(vector, join="inner")
        n = len(q)
        if n < 10:
            if args.verbose:
                print("Skipping", row.name, "(not enough data)",
                    file=sys.stderr)
            continue
        r,p = pearsonr(q,v)
        if np.isnan(r) and not args.print_all:
            continue
        p = - np.log10(p)
        print(row.name, n, r, p, sep="\t")
