#!/usr/bin/env python3

import argparse
import itertools
import sys

p = argparse.ArgumentParser()
p.add_argument("--fields", "-f")
p.add_argument("--names", "-n")
p.add_argument("--delimiter", "-d", default="\t")
p.add_argument("file", type=argparse.FileType("r"),
        default=sys.stdin, nargs="?")
args = p.parse_args()

if args.fields and args.names:
    print("conflicting options: -f and -n", file=sys.stderr)
    sys.exit(1)
if not args.fields and not args.names:
    print("one of -f and -n is required", file=sys.stderr)
    sys.exit(1)

header = next(args.file)
if args.names:
    fields = []
    name_position = dict(map(reversed,enumerate(header.split(args.delimiter))))
    for n in args.names.split(","):
        n = n.strip('"').strip("'")
        try:
            fields.append(name_position[n])
        except KeyError:
            print("no such column:", n, file=sys.stderr)
else:
    fields = list(map(int, fields.split(",")))

lines = itertools.chain([header], args.file)
for line in lines:
    xs = line.rstrip("\n").split(args.delimiter)
    print(*[xs[i] for i in fields], sep=args.delimiter)
