#!/usr/bin/env python3

# Split a matrix's rows using a mapping.

import argparse
import collections
import os
import sys
import gzip

p = argparse.ArgumentParser()
p.add_argument("map", type=argparse.FileType("r"))
p.add_argument("--column", "-c", default=1, type=int)
p.add_argument("--outdir", "-o", default=".")
args = p.parse_args()

map = collections.defaultdict(list)
with args.map as h:
    for line in h:
        key, value = line.strip("\n").split("\t")
        map[key].append(value)

files = {}

try:
    header = next(sys.stdin)
    for line in sys.stdin:
        key = line.strip("\n").split("\t")[args.column - 1]
        tkeys = map.get(key)
        if not tkeys:
            continue
        for tkey in tkeys:
            if not tkey in files:
                path = os.path.join(args.outdir, tkey) + ".gz"
                files[tkey] = gzip.open(path, "wt")
                files[tkey].write(header)
            files[tkey].write(line)
finally:
    for h in files.values():
        h.close()
