#!/usr/bin/env python

from argparse import ArgumentParser, ArgumentTypeError
import random
import sys

def check_bounds(x):
    try:
        x = float(x)
    except:
        raise ArgumentTypeError("probability must be float")
    if x <= 0 or x > 1:
        raise ArgumentTypeError("probability must within (0-1]")
    return x

p = ArgumentParser()
p.add_argument("--probability", "-p", 
    required=True, type=check_bounds)
p.add_argument("--no-header", "-H",
        action="store_true")
args = p.parse_args()

if not args.no_header:
    print(next(sys.stdin), end="")
for line in sys.stdin:
    if random.random() < args.probability:
        print(line, end="")
