#!/usr/bin/env python3

import sys

import click

import BioTK.io
from BioTK.matrix.preprocess import standardize as _standardize

def standardize(header=True):
    BioTK.io.read_matrix(sys.stdin, header=header)\
        .apply(_standardize)\
        .dump()

@click.command()
@click.option("--no-header", "-H", is_flag=True)
def main(no_header):
    standardize(header=not no_header)

if __name__ == "__main__":
    main()
