#!/usr/bin/env python3

import sys

import numpy as np

from BioTK.io import read_matrix

def gini(x):
    x = np.array(x.dropna())
    n = len(x)
    if n <= 1:
        return np.nan
    x.sort()
    x += (1 - x.min())
    o = 1 + (1 / n)
    o -= (2 * (x * np.arange(n, 0, -1)).sum()) / (n * x.sum())
    assert (o <= 1) and (o >= 0)
    return o


print("", "N", "Sum", "Mean", "SD", "Gini", sep="\t")
for row in read_matrix(sys.stdin):
    rs = (row.sum(), row.mean(), row.std(), gini(row))
    n = (~row.isnull()).sum()
    print(row.name, n, *["%0.3f" % x for x in rs], sep="\t")
