#!/usr/bin/env bash

source $(dirname $0)/BioTK.sh

buffer_size=20%
while getopts :S: opt; do
    case $opt in
        S) buffer_size=$OPTARG ;;
    esac
done

LC_COLLATE=C dt wrap \
    sort -t$'\t' --compress-program="$FAST_COMPRESS_PROGRAM" --parallel=8 \
    -S $buffer_size \
    "$@"
