#!/usr/bin/env python3

import sys
import gzip

import numpy as np

def index(seq):
    return dict(map(reversed, enumerate(seq)))

def gzopen(path):
    if path.endswith(".gz"):
        return gzip.open(path, "rt")
    else:
        return open(path)

def as_float(x):
    try:
        return float(x)
    except ValueError:
        return np.nan

if len(sys.argv) < 2:
    sys.stderr.write("USAGE: dm union <table> ...\n")
    sys.exit(1)

columns = set()
for path in sys.argv[1:]:
    with gzopen(path) as h:
        try:
            for c in next(h).strip("\n").split("\t")[1:]:
                columns.add(c)
        except StopIteration:
            pass

columns = list(sorted(columns))
columns_ix = index(columns)
print("", *columns, sep="\t")

def handle_file(h):
    m = {}
    for i,c in enumerate(next(h).strip("\n").split("\t")[1:]):
        j = columns_ix[c]
        m[i] = j

    for line in h:
        key, *data = line.strip("\n").split("\t")
        xs = np.empty(len(columns))
        xs[:] = np.nan
        for i,x in enumerate(data):
            xs[m[i]] = as_float(x)
        print(key, *xs, sep="\t")


for path in sys.argv[1:]:
    with gzopen(path) as h:
        try:
            handle_file(h)
        except StopIteration:
            pass
