#!/usr/bin/env python3

import sys

import pandas as pd

if len(sys.argv) > 1:
    path = sys.argv[1]
else:
    path = "/dev/stdin"

pd.read_pickle(path)\
    .to_csv(sys.stdout, sep="\t", float_format="%0.3f")

