#!/usr/bin/env bash

nr=10
nc=5

while getopts r:c: opt; do
    case $opt in
        r) nr=$OPTARG ;;
        c) nc=$OPTARG ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -gt 0 ]; then
    cat $1
else
    cat
fi | head -$nr | cut -f1-$nc
