#!/usr/bin/env bash

while getopts p opt; do
    case $opt in
        p) parallel=y ;;
    esac
done

shift $((OPTIND - 1))

IFS="" read -r header
echo "$header"
#nc=$(echo "$header" | tr '\t' '\n' | sed 1d | wc -l)
#nl=$((1 + (nc / 100)))

if [ -z $parallel ]; then
    "$@"
else
    parallel --tmpdir "$TMPDIR" -P150% --block-size 50M --pipe "$@"
fi
