#!/usr/bin/env bash

# Either mean or median 

# Takes VW format (or just straight numbers) on stdin

dat=$(mktemp)
trap 'rm -f $dat' EXIT
cut -d' ' -f1 > $dat
n=$(wc -l < $dat)
mean=$(awk '{x+=$1} END {print x/NR}' < $dat)
median=$(sort -nk1 $dat | awk -v n=$n 'NR > (n / 2) { print; exit; }') 

yes $mean | head -$n
