#!/usr/bin/env python

import argparse

import psycopg2

p = argparse.ArgumentParser()
p.add_argument("--taxon_id", "-t", type=int, required=True)
args = p.parse_args()

db = psycopg2.connect("dbname=BioTK")
c = db.cursor()

c.execute("""SELECT id FROM gene WHERE taxon_id=%s ORDER BY id""" % args.taxon_id)
columns = [x[0] for x in c]

c = db.cursor("q")
print("Sample ID", *columns, sep="\t")
c.execute("""
SELECT geo_sample.id, data
FROM geo_sample 
INNER JOIN geo_platform
ON geo_sample.platform_id=geo_platform.id
WHERE geo_platform.taxon_id=%s
AND data IS NOT NULL 
""" % args.taxon_id)

while True:
    rows = c.fetchmany(10)
    if not rows:
        break
    for sample_id, data in rows:
        print(sample_id, *data, sep="\t")
