#!/usr/bin/env python

import argparse
import psycopg2

p = argparse.ArgumentParser()
p.add_argument("--host", "-H", 
        default="db.wren.omrf.hsc.net.ou.edu")
p.add_argument("--database", "-d",
        default="dev")
p.add_argument("--port", "-p", type=int, default=5432)
p.add_argument("--taxon-id", "-t", type=int, required=True)
p.add_argument("-n", type=int)

args = p.parse_args()

db = psycopg2.connect(
        host=args.host,
        port=args.port,
        database=args.database)

c = db.cursor()
c.execute("""
SELECT id 
FROM gene
WHERE taxon_id=%s
ORDER BY id;""", (args.taxon_id,))
genes = [row[0] for row in c]

q = """
SELECT ch.sample_id, ch.channel, gene_data 
FROM channel ch
WHERE gene_data IS NOT NULL 
AND ch.taxon_id=%s"""
if args.n:
    q += " LIMIT %s" % args.n

c.execute(q, (args.taxon_id,))

print("-", *genes, sep="\t")
for id, ch, data in c:
    print("%s-%s" % (id,ch), *[x if x else "" for x in data],
            sep="\t")
