#!/usr/bin/env bash

source $(dirname $0)/BioTK.sh

taxon_id=9606
while getopts t: opt; do
    case $opt in 
        t) taxon_id="$OPTARG" ;;
    esac
done

cache_download ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene_info.gz \
    | gzip -cd \
    | tawk -v t="$taxon_id" '$1 == t { print $2,$11; print $2,$12; split($5,ss,"|"); for (i in ss) { print $2,ss[i] } }' \
    | tawk '$2 != "-"' \
    | sort -u \
    | sort -k1b,1
