#!/usr/bin/env bash

# Perform operations on GEO data and query GEOmetadb

source $(dirname $0)/BioTK.sh

cmd="$1"

which geo-"$cmd" &> /dev/null || {

    cat 1>&2 <<EOF
geo - Fetch and manipulate data from NCBI GEO

Available subcommands:

    build-db - Download and build all GEO data matrices
    fetch - Download and compress MiniML data
    extract - Extract a matrix from a MiniML archive
    label - Extract labels from GEO metadata
EOF
    exit 0
}

shift
geo-${cmd} "$@"
