#!/usr/bin/env bash

usage() {
    cat <<EOF 1>&2
Download, reorder, and LZMA compress GEO platform data in MiniML format.

USAGE: $0 [-o outdir] GPL1234 GPL4567 ...
EOF
}

outdir=$(pwd)
key=~/.aspera/connect/etc/asperaweb_id_dsa.openssh
host=anonftp@ftp.ncbi.nlm.nih.gov
tmpdir=$(mktemp -d)
speed=200M

trap "rm -rf $tmpdir" EXIT

while getopts h opt; do
    case $opt in
        o) outdir=$(realpath "$OPTARG") ;;
        h) usage && exit 0 ;;
        *) usage && exit 1 ;;
    esac
done
shift $((OPTIND - 1))

for accession in "$@"; do
    if [ ${#accession} -lt 6 ]; then
        group=GPLnnn
    else
        group=${accession:0:-3}nnn
    fi
    uri=/geo/platforms/${group}/${accession}/miniml/
    wd=$tmpdir/$accession

    echo "* Downloading $accession ..." 1>&2
    ascp -l $speed -d -i $key $host:$uri $tmpdir #&> /dev/null
    mv $tmpdir/miniml $wd
    echo "* Decompressing $accession data ..." 1>&2
    for file in $wd/*.tgz; do
        tar -C $wd -zxf $file
    done
    rm $wd/*.tgz
    echo "* Compressing $accession data ..." 1>&2
    ( cd $wd ; tar -cf - * | pixz -0 > "$outdir"/${accession}.tar.xz )
    echo "* Cleaning up temporary files ..." 1>&2
    rm -rf $wd
done
