#!/usr/bin/env python3

import BioTK.io

class Record(object):
    __slots__ = [ "accession","channel",
        "title","source_name","characteristics"]
    def __init__(self, *data):
        assert len(self.__slots__) == len(data)
        for k,item in zip(self.__slots__, data):
            setattr(self, k, item)

def records():
    db = sqlite3.connect("GEOmetadb.sqlite")
    c = db.cursor()
    for i in range(1,3):
        q = """
            SELECT
                gsm
                title,
                description,
                source_name_ch%s,
                characteristics_ch%s
            FROM gsm
            WHERE channel_count>=%s
        """ % (i,i,i)
        c.execute(q)
        for key,*rest in c:
            yield Record(key,i,*rest)

#for r in records():
#    print(r.accession)
#    break

url = "http://gbnci.abcc.ncifcrf.gov/geo/GEOmetadb.sqlite.gz"
path = BioTK.io.download(url, unzip="gzip", open=False)
print(path)
