#!/usr/bin/env bash

source $(dirname $0)/BioTK.sh

url="http://gbnci.abcc.ncifcrf.gov/geo/GEOmetadb.sqlite.gz"

db="$CACHE/GEOmetadb.sqlite"
if [ ! -f "$db" ]; then
    curl "$url" | gzip -cd > "$db"
fi

for i in $(seq 2); do
    sqlite3 -separator $'\t' "$db" \
        "SELECT gsm || '-$i', source_name_ch$i FROM gsm LIMIT 5"
done \
    | tm match \
        -i <( (ontology names BTO && ontology synonyms BTO) | sort -u )
