#!/usr/bin/env bash

while getopts o:p: opt; do
    case $opt in
        o) out="$OPTARG" ;;
        p) path="$OPTARG" ;;
    esac
done

tmp=$(mktemp)
trap "rm -f $tmp" EXIT

zcat -f | lz4 -q > $tmp
dim=( $(lz4 -dq $tmp | sed 1d | cut -f2- | dims) )


h5import <(lz4 -dq $tmp | sed 1d | cut -f2-) -c <(cat <<EOF
PATH $path
INPUT-CLASS TEXTFP 
RANK 2 
DIMENSION-SIZES ${dim[@]}
OUTPUT-CLASS FP 
OUTPUT-SIZE 64 
OUTPUT-ARCHITECTURE IEEE 
OUTPUT-BYTE-ORDER LE
EOF
) -o $out
