#!/usr/bin/env python

import argparse
import sys

import numpy as np
from pylab import hist, plot, savefig, xlabel, ylabel, title

import BioTK.plot

p = BioTK.plot.argparse_template()
p.add_argument("--bins", "-b", type=int, default=10)
args = p.parse_args()

x = []
for line in sys.stdin:
    try:
        v = float(line)
        if np.isnan(v):
            continue
        x.append(v)
    except ValueError:
        continue

#n, bins, patches = hist(x, args.bins, color=args.color)
BioTK.plot.histogram.cli(args, x)
