#!/usr/bin/env python3

import sys

from BioTK.io import read_matrix
from BioTK.matrix.preprocess import log_transform

if __name__ == "__main__":
    read_matrix(sys.stdin)\
        .apply(log_transform, base=2, range=100, shift=True)\
        .dump()
