#!/usr/bin/env bash

fifos=()
tmpdir=$(mktemp -d)
trap 'rm -rf $tmpdir' EXIT

for file in "$@"; do
    fifo=$(mktemp -p $tmpdir)
    rm $fifo
    mkfifo $fifo
    lz4 -dq $file > $fifo &
    fifos+=($fifo)
done

paste "${fifos[@]}"
