#!/usr/bin/env bash

# $1 - matrix
# $2 - AILUN

[[ $# -ne 2 ]] && {
    echo "USAGE: $0 matrix.gz AILUN.annot.gz" 1>&2
    exit 1
}

zcat $1 | head -1000 \
    | mean \
    | sort -k1b,1 \
    | join -t'	' - <(zcat $2 | sort -k1b,1) \
    | sort -rnk2 \
    | cut -f1,3
