#!/usr/bin/env python3

import argparse
import sys

import click
import networkx as nx

from BioTK.io.OBO import parse

@click.group()
def cli():
    pass

@cli.command()
def terms():
    ontology = parse(sys.stdin)
    ontology.terms.to_csv(sys.stdout, sep="\t")

@cli.command()
def synonyms():
    ontology = parse(sys.stdin)
    ontology.synonyms.to_csv(sys.stdout, sep="\t")

@cli.command()
def relations():
    ontology = parse(sys.stdin)
    ontology.relations.to_csv(sys.stdout, sep="\t", index=False)

def _print_descendants_or_ancestors(fn, term):
    ontology = parse(sys.stdin)
    relations = set(ontology.relations.iloc[:,2])
    graph = ontology.to_graph(relations=relations)
    for t in fn(graph, term):
        name = ontology.terms["Name"][t]
        print(t, name, sep="\t")

@cli.command()
@click.argument("term")
def descendants(term):
    _print_descendants_or_ancestors(nx.ancestors, term)

@cli.command()
@click.argument("term")
def ancestors(term):
    _print_descendants_or_ancestors(nx.descendants, term)

if __name__ == "__main__":
    cli()
