#!/usr/bin/env bash

source $(dirname $0)/BioTK.sh

cmd="$1"
ontology=$(echo $2 | tr '[A-Z]' '[a-z]')
url="http://www.berkeleybop.org/ontologies/${ontology}.obo"
shift 2
cache_download "$url" | obo $cmd $@
