#!/usr/bin/env python3

import sys

import BioTK.statistics

X = BioTK.io.read_matrix(sys.stdin).to_frame()
v = BioTK.io.read_vector(sys.argv[1])

BioTK.statistics.partial_correlation(X,v)\
        .to_csv(sys.stdout, 
                sep="\t", float_format="%0.3f")
