#!/usr/bin/env bash

color="green"

while getopts t:x:y: opt; do
    case $opt in 
        x) xlabel="$OPTARG" ;;
        y) ylabel="$OPTARG" ;;
        t) title="$OPTARG" ;;
        c) color="$OPTARG" ;;
    esac
done

export xlabel ylabel title

dat=$(mktemp)
trap 'rm -f $dat' EXIT
cat > $dat

ymax=$(echo $(cut -f2 $dat | sort -rn | head -1) '* 1.1' | bc)
echo $ymax 1>&2

gnuplot <(cat <<EOF
load '$(dirname $0)/common.gpi'

set title '$title'
set xlabel '$xlabel'
set ylabel '$ylabel'

# Don't show legend
set ytics out

set yrange [0:$ymax]
set xtics nomirror rotate by -45
set boxwidth 0.85

plot '$dat' using 2: xtic(1) with boxes linecolor rgb '$color'
EOF)
