#!/usr/bin/env bash

dat=$(mktemp)
trap 'rm -f $dat' EXIT
grep -v '^$' | sort -n > $dat

min=$(head -1 $dat)
max=$(tail -1 $dat)
bins=25
color="green"

while getopts t:x:y:l:u: opt; do
    case $opt in
        t) title="$OPTARG" ;;
        x) xlabel="$OPTARG" ;;
        y) ylabel="$OPTARG" ;;
        c) color="$OPTARG" ;;
        n) bins="$OPTARG" ;;
        l) min="$OPTARG" ;;
        u) max="$OPTARG" ;;
    esac
done

gnuplot <(cat <<EOF
load '$(dirname $0)/common.gpi'

Min = $min
Max = $max
bins = $bins
width = (Max-Min)/bins
bin(x)=width*(floor((x-Min)/width)+0.5) + Min

set xrange [Min:Max]
set xlabel '$xlabel'
set ylabel '$ylabel'
set title '$title'

plot '$dat' using (bin(\$1)):(1.0) smooth freq with boxes lc rgb "$color"
EOF
)
