#!/usr/bin/env python

import sys

with open(sys.argv[1]) as h:
    ix = set(line.strip("\n") for line in h)

print(next(sys.stdin), end="")

for line in sys.stdin:
    key = line.split("\t", 1)[0]
    if key in ix:
        print(line, end="")
