#!/usr/bin/env python3

import argparse
import sys

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("columns", type=argparse.FileType("r"))

    header = next(sys.stdin)
    header_fields = header.strip("\n").split("\t")
    header_map = dict(list(map(reversed, enumerate(header_fields))))

    column_ix = []
    # By default, if the first column header is either "" or "-",
    # it is assumed to be in a matrix-like format and the first column
    # is printed, even when not explicitly selected
    if header_fields[0] in ("", "-"):
        column_ix.append(0)

    with open(sys.argv[1]) as h:
        for line in h:
            name = line.strip("\n")
            ix = header_map.get(name)
            if ix is not None:
                column_ix.append(ix)

    print(*[header_fields[ix] for ix in column_ix], sep="\t")
    for line in sys.stdin:
        fields = line.strip("\n").split("\t")
        print(*[fields[ix] for ix in column_ix], sep="\t")
