#!/usr/bin/env python

import sys

import pandas as pd

import btk

groups = pd.read_table(sys.argv[1], 
        compression=("gzip" if sys.argv[1].endswith(".gz") else None))
groups = groups.drop_duplicates([groups.columns[0]])
index = groups.iloc[:,0]
groups = groups.iloc[:,1]
groups.index = index

with btk.MatrixReader(sys.stdin) as h:
    name, *columns = next(h)
    print(name, *columns, sep="\t")
    for name, data in h:
        series = pd.Series(data, index=columns)
        for g,df in series.groupby(groups):
            series.ix[df.index] = (df - df.mean()) / df.std()
        print(name, *series, sep="\t")
