#!/usr/bin/env python3

import sys

import BioTK.io
from BioTK.matrix.preprocess import standardize

if __name__ == "__main__":
    BioTK.io.read_matrix(sys.stdin)\
        .apply(standardize)\
        .dump()
