#!/usr/bin/env bash

while getopts y: opt; do
    case $opt in
        y) y="$OPTARG" ;;
    esac
done

header=$(mktemp)
trap 'rm -f $header' EXIT
read line

# Remove colons and fix IDs starting with numbers which will confuse vw
echo "$line" \
    | tr '\t' '\n' \
    | sed ${y}d \
    | sed 's/:/_/g;s/^\([0-9]\)/X\1/' \
    > $header

while read line; do
    key=$(echo "$line" | tr '\t' '\n' | sed "${y}q;d")
    echo -ne "$key | "
    echo "$line" | tr '\t' '\n' | sed ${y}d | paste $header - \
        | awk '$1 != "" && $2 != "" { \
            m = match($2, /^[0-9\.\-]/); \
            if (m) { \
                printf "%s:%s ",$1,$2 } \
            else { \
                printf "%s_%s ",$1,$2 } \
        }'
    echo
done 
