#!/usr/bin/env python

import argparse
import gzip
import os
import sys
import subprocess
import tempfile

p = argparse.ArgumentParser()
p.add_argument("--delimiter", "-d", default="\t")
args = p.parse_args()

dir = tempfile.TemporaryDirectory()
lines = []
chunk_size = 100

def write_lines(i, lines):
    g = i // chunk_size
    p = os.path.join(dir.name, "%06d" % g)
    with open(p, "wt") as h:
        for fs in zip(*[line.strip("\n").split(args.delimiter)
            for line in lines]):
            h.write(args.delimiter.join(fs) + "\n")
            
for i, line in enumerate(sys.stdin):
    lines.append(line)
    if i and i % chunk_size == 0:
        write_lines(i, lines)
        lines = []
if lines:
    write_lines(i, lines)

devnull = open(os.devnull, "w")
files = [os.path.join(dir.name, f) for f in 
        sorted(os.listdir(dir.name))]
subprocess.call(["paste"] + files,
        stdout=sys.stdout, stderr=devnull)
