#!/usr/bin/env python3

import sys

import pandas as pd
import sklearn.manifold

import BioTK

X = BioTK.io.read_matrix(sys.stdin).to_frame()
model = sklearn.manifold.TSNE()
o = model.fit_transform(X)
pd.DataFrame(o,
        index=X.index, columns=["C"+str(i+1) for i in range(o.shape[1])])\
                .to_csv(sys.stdout, sep="\t")
