#!/usr/bin/env python3

import sys

import numpy as np

import BioTK

for i,row in enumerate(BioTK.io.read_matrix(sys.stdin)):
    for j,v in enumerate(row):
        if not np.isnan(v):
            print(i,j,v,sep="\t")
