#!/usr/bin/env bash

CACHE="$HOME/.local/cache/urlcache"
mkdir -p "$CACHE"

usage() {
    cat <<EOF 1>&2
Download a URL to the local disk, or read from disk if it was previously downloaded.
In either case, write the file contents to stdout.

USAGE: $0 <options> URL

options:
  -p : Instead of writing the file contents to stdout, write
    the full path to the cached file.
  -f <filter-cmd> : Filter the downloaded file using the given
    command before saving it. 
EOF
    exit 1
}

filter_cmd=cat
return_path=

while getopts hpf: opt; do
    case $opt in
        f) filter_cmd="$OPTARG" ;;
        p) return_path=y ;;
        h) usage ;;
    esac
done

shift $((OPTIND - 1))
[ $# != 1 ] && usage

url="$1"
md5=$(echo $url | md5sum | awk '{ print $1 }')
path="$CACHE/$md5"

if [ ! -e "$path" ]; then
    curl -L -o "$path" "$url" 2> /dev/null > "$path" || {
        rm -f "$path"
        exit 1
    }
    cat "$path" | $filter_cmd | buffer -o "$path"
fi

if [[ $return_path == "" ]]; then
    cat "$path"
else
    echo "$path"
fi
