#!/usr/bin/Rscript --vanilla

library(VennDiagram)
library(optparse)

options = list(
    make_option(c("--output", "-o"), type="character", default="venn.png")
)
parser = OptionParser(option_list=options)
args = parse_args(parser, positional_arguments=c(2,4))

sets = lapply(args$args, function(path) {
    readLines(path)
})
names(sets) = args$args

venn.diagram(sets, 
             args$options$output, 
             force.unique=T,
             imagetype="png", 
             compression="none")

# vim: set ft=r :
