#!/usr/bin/env bash

model=$(mktemp -p /dev/shm)
dat=$(mktemp -p /dev/shm)
trap 'rm -f $model $dat' EXIT
lz4 > $dat

lz4 -dq $dat | vw -f $model -c --passes 10 &> /dev/null
lz4 -dq $dat | vw -i $model -p /dev/stdout 2> /dev/null
