#!/usr/bin/env bash

model=$(mktemp -p /dev/shm)
dat=$(mktemp -p /dev/shm)
splits=$(mktemp -d -p /dev/shm)
trap 'rm -rf $model $dat $splits' EXIT

cat > $dat
split -n l/5 $dat $splits/x
rm $dat

for file in $splits/*; do
    #ls $splits/* | grep -v $file 1>&2
    cat $(ls $splits/* | grep -v $file) \
        | vw --rank 2 --invariant -f $model &> /dev/null
    vw -i $model -t -p /dev/stdout 2> /dev/null < $file
    rm -f $model
done | paste <(cat $splits/* | awk '{print $1}') -

#paste \
#    <(lz4 -dq $dat | awk '{print $1}') \
#    <(lz4 -dq $dat | vw -i $model -p /dev/stdout 2> /dev/null)
