#!/usr/bin/env bash

# Create a VW template from a tab-delimited matrix

# Use up to 10% of total RAM for sort buffer
bufsz=$(grep MemTotal /proc/meminfo | awk '{printf "%d", ($2 * 0.1)}')
header=$(mktemp)
trap 'rm -f $header' EXIT
read line

# Remove colons which will confuse vw
echo "$line" | tr '\t' '\n' | sed 1d | sed s/:/_/g > $header

while read line; do
    key=$(echo "$line" | tr '\t' '\n' | head -1)
    echo -ne "$key\t"
    echo "$line" | tr '\t' '\n' | sed 1d | paste $header - | awk '$1 != "" && $2 != "" { printf "%s:%s ",$1,$2 }'
    echo
done | sort -k1b,1 -S $bufsz
