#!/usr/bin/env python

import sys
import argparse

import pandas as pd

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--mapping", "-m", required=True,
                   type=argparse.FileType("r"))
    p.add_argument("matrix", default=sys.stdin,
                   nargs="?",
                   type=argparse.FileType("r"))
    args = p.parse_args()

    mapping = {}
    for line in args.mapping:
        fields = line.strip("\n").split("\t")
        if len(fields) == 2:
            mapping[fields[0]] = fields[1]

    X = pd.read_table(args.matrix, sep="\t", header=0, index_col=0)

    def max_mean(X):
        mu = X.mean(axis=1)
        mu.sort(ascending=False)
        return X.ix[mu.index[0],:]

    X.groupby(mapping).apply(max_mean)\
        .to_csv(sys.stdout, sep="\t")
