#!/usr/bin/env python

import argparse
import sys

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--mapping", "-m", required=True,
                   type=argparse.FileType("r"))
    p.add_argument("--skip-header", "-H",
                   action="store_true")
    args = p.parse_args()

    mapping = {}
    for line in args.mapping:
        fields = line.strip("\n").split("\t")
        if len(fields) == 2:
            mapping[fields[0]] = fields[1]

    if args.skip_header:
        print(next(sys.stdin), end="")

    for line in sys.stdin:
        key, rest = line.strip("\n").split("\t", 1)
        value = mapping.get(key)
        if value is not None:
            print(value, rest, sep="\t")
