#!/usr/bin/env python

import numpy as np

import btk

@btk.matrix_map
def log_transform(label, x):
    if x.max() - x.min() > 100:
        x = x.apply(np.log2)
    return label, x

log_transform.run()
