#!/usr/bin/env bash

read -d '' q <<EOF
COPY (
    SELECT q.pmid, citations.title || ' ' || q.abstract_text as text
    FROM
    ( 
        SELECT sections.pmid, string_agg(' ', sections.content) AS abstract_text
        FROM sections
        GROUP BY sections.pmid
    ) q
    INNER JOIN citations
    ON citations.pmid=q.pmid
) 
TO STDOUT WITH DELIMITER '	';
EOF

psql -d medline -c "$q"
