#!/usr/bin/env python

import sys

import btk

with btk.FieldReader(sys.stdin) as h:
    print(*next(h), sep="\t")
    for fields in h:
        if not all(x in ('NaN', '') for x in fields[1:]):
            print(*fields, sep="\t")
