#!/usr/bin/env python

import sys

import numpy as np
import pandas as pd

import BioTK.expression

if __name__ == "__main__":
    # Read & clean out columns w/ bad data
    X = pd.read_csv(sys.stdin, sep="\t", index_col=0)
    X.drop([c for c in X.columns 
        if X[c].dtype==np.dtype('O') or c.startswith("Unnamed")], 
        axis=1, inplace=True)
    X.dropna(axis=0, thresh=int(X.shape[1] * 0.1), inplace=True)
    X.dropna(axis=1, thresh=int(X.shape[0] * 0.1), inplace=True)

    # Impute missing values as mean of that gene's expression
    # (simple, I know)
    X = X.apply(lambda x: x.fillna(x.mean()), axis=1)
    # Quantile normalize
    X = BioTK.expression.quantile_normalize(X)
    # Standardize by gene
    X = X.T.apply(lambda x: (x - x.mean()) / x.std()).T

    X.to_csv(sys.stdout, sep="\t", float_format="%0.3f")
