#!/usr/bin/env python

import sys

import btk

input = btk.FieldReader(sys.stdin)

header = next(input)
ix = btk.index_positions(header)

def select(xs):
    return [xs[ix[x]] if x in ix else "" for x in sys.argv[1:]]

print(*select(header), sep="\t")

for fields in input:
    print(*select(fields), sep="\t")
