#!/usr/bin/env python

import sys
import numpy as np

accessions = next(sys.stdin).strip("\n").split("\t")[1:]
sum = np.zeros(len(accessions))
n = np.zeros(len(accessions))

for line in sys.stdin:
    fields = line.strip("\n").split("\t")[1:]
    data = np.array([float(x) if x else np.nan for x in fields])
    ix = ~np.isnan(data)
    sum[ix] += data[ix]
    n[ix] += 1

for i,accession in enumerate(accessions):
    if n[i] == 0:
        continue
    print(accession, sum[i] / n[i], sep="\t")
