#!/usr/bin/env python

import sys

import pandas as pd

i = int(sys.argv[1]) - 1
j = int(sys.argv[2]) - 1
x = int(sys.argv[3]) if len(sys.argv) > 3 else None

X = pd.read_table(sys.stdin)
X = X.drop_duplicates(subset=X.columns[[i,j]])
X["Value"] = 1
X.pivot(X.columns[i], X.columns[j], values=X.columns[x] if x 
        else X.columns[-1])\
                .fillna(0)\
                .astype(int)\
                .to_csv(sys.stdout,sep="\t")\
