#!/usr/bin/env python

import sys
j = int(sys.argv[1]) - 1

handles = {}
header = next(sys.stdin)
for line in sys.stdin:
    key = line.strip("\n").split("\t")[j]
    if not key in handles:
        handles[key] = open(key, "w")
        print(header.strip("\n"), file=handles[key])
    print(line.strip("\n"), file=handles[key])
