#!/usr/bin/env bash

usage() {
    cat <<EOF 1>&2
USAGE: $0 <options>

Read and transpose a matrix from stdin. 

Options:
  -m : perform the entire transpose in RAM
  -l <count> : number of lines to transpose at a time;
    a larger number requires more RAM
    (default: 250)
EOF
    exit $1
}

tmpdir=$HOME/.cache/btk
mkdir -p $tmpdir

lines=250

while getopts ml: opt; do
    case $opt in
        m) tmpdir=/dev/shm ;;
        l) lines="$OPTARG" ;;
        h) usage 0 ;;
    esac
done

wd=$(mktemp -d -p $tmpdir)
trap 'rm -rf $wd' SIGHUP SIGINT SIGTERM ERR

process() {
    lz4 -dq $1 | transpose-block | lz4 -q > ${1}.tmp
    mv ${1}.tmp $1
}
export -f process

split -l $lines --filter='lz4 > $FILE' - $wd/x
parallel process ::: $wd/x*
zpaste $wd/*
rm -rf $wd
