#!/usr/bin/env bash

usage() {
    echo "Translate elements in a column to values"
    echo "	specified by a key-value mapping file."
    echo "USAGE: dm translate [-c col] <map-file> < input-data"
    exit $1
} 1>&2

column=1
while getopts c:h opt; do
    case $opt in
        c) column="$OPTARG" ;;
        h) usage 0 ;;
        ?) usage 1 ;;
    esac
done
shift $((OPTIND - 1))

tjoin -1 $column -2 1 - $1 \
    | cut -f2- \
    | tawk -v c="$column" '{ \
        tmp=$NF; \
        for (i=NF; i>c; i--) { \
            $i=$(i-1) \
        }; \
        $c=tmp; \
        print \
    }'
