{
 :database 
 {:subprotocol "postgresql"
  :subname "//wren.omrf.hsc.net.ou.edu:5432/dev2"
  ;:subname "//localhost:5432/dev"
  :user "gilesc"
  :species
  ["Homo sapiens"
   "Mus musculus"
   "Rattus norvegicus"
   "Arabidopsis thaliana"
   "Saccharomyces cerevisiae"
   "Sus scrofa"
   "Escherichia coli"
   "Caenorhabditis elegans"
   "Bos taurus"
   "Danio rerio"
   "Zea mays"
   "Oryza sativa"
   "Halobacterium sp. NRC-1"
   "Gallus gallus"
   "Macaca mulatta"
   "Streptomyces coelicolor"
   "Mycobacterium tuberculosis"
   "Campylobacter jejuni"
   "Mycobacterium tuberculosis H37Rv"
   "Pimephales promelas"
   "Canis lupus familiaris"
   "Bacillus subtilis"
   "Daphnia magna"
   "Staphylococcus aureus"
   "Salmonella enterica subsp. enterica serovar Typhimurium"
   "Plasmodium falciparum"
   "Glycine max"
   "Synechocystis sp. PCC 680"
   "Streptococcus mutans UA159"
   "Xenopus laevis"
   "Oryza sativa Japonica Group"
   "Equus caballus"
   "Bacillus subtilis subsp. subtilis str. 168"
   "Aedes aegypti"
   "Haemophilus influenzae"]}
 :ui
 {:port 5678}
 }
